# Generated by Django 3.0.8 on 2020-07-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('screen', models.CharField(max_length=20)),
                ('Rate', models.CharField(max_length=20)),
            ],
        ),
    ]
