# Generated by Django 3.0.8 on 2020-07-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20200710_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='Wallet',
            field=models.CharField(default=50, max_length=20),
        ),
    ]
