# Generated by Django 3.0.8 on 2020-07-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_auto_20200711_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
