# Generated by Django 3.0.8 on 2020-07-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_auto_20200711_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='poster_link',
            field=models.CharField(default='https://xl.movieposterdb.com/19_12/2017/3890160/xl_3890160_081e65b0.jpg', max_length=1000),
        ),
    ]
